### ISSUE TITLE
Check the HTML and furigana situation

### ISSUE THREAD

**Issue by HelenFoster** [HelenFoster/JSentenceHighlighter#5]
This just came up in KanjiVocab, so after sorting that out, see if anything can be improved here.

https://github.com/HelenFoster/KanjiVocab/issues/8

**Comment by kanjieater** [comment]
I think I just ran into this.  Using the new MIAJapaneseSupport for reading generation due to it generating pitch accent with a slightly different format.　

Reading field: `ここ[;h] から 先[さき;a]は 隣[となり;h] の 国[くに;h] の 領土[りょうど;a] です[;a] 。`
Vocab field: 領土

It would be ideal to generate this:
`ここ[;h] から 先[まず;a]は 隣[となり;h] の 国[くに;h] の <b>領土[りょうど;a]</b> です[;a] 。`
But I get this:
`ここ[;h] から 先[まず;a]は 隣[となり;h] の 国[くに;h] の <b>領土</b>[りょうど;a] です[;a] 。`
Which won't be read as furigana.

I can make a new issue if this isn't what you intended to address here.

**Comment by HelenFoster** [comment]
Right, that would be relevant here. I'll see what I can do when I get onto this.

**Comment by HelenFoster** [comment]
I think I solved this!

@kanjieater Please let me know how it works out with your real cards.
